---
- hosts: front
  sudo: yes
  vars:
    packages: 
      - nginx
      - memcached
  tasks:
      # TODO:  Find a better way to do this!  UG-LY
    - name: add yum repo for nginx
      command: rpm -i --force http://nginx.org/packages/centos/6/noarch/RPMS/nginx-release-centos-6-0.el6.ngx.noarch.rpm
    - name: install packages
      yum: pkg={{ item }} state=latest
      with_items: packages
  handlers:
    - name: restart nginx
      service: name=nginx state=restarted
    - name: restart memcached
      service: name=memcached state=restarted

- hosts: app
  sudo: yes
  vars:
    packages: 
      - httpd
      - php
      - mysql-server
  tasks:
    - name: install packages
      yum: pkg={{ item }} state=latest
      with_items: packages
  handlers:
    - name: restart httpd
      service: name=httpd state=restarted
    - name: restart php
      service: name=php state=restarted
    - name: restart mysql-server
      service: name=myself-server state=restarted


