---

# TODO: Don't dup IPs (currently duplicated in Vagrant file, must be manually synched)
- name: Update hosts file
  lineinfile: dest=/etc/hosts state=present line="192.168.1.101 app"

- name: Copy rules and enable firewall
  copy: src=iptables dest=/etc/sysconfig/iptables backup=yes
#  notify: restart iptables

- name: Update nginx config
  copy: src=default.conf dest=/etc/nginx/conf.d/default.conf backup=yes
  notify: restart nginx

