---

# TODO: Only write if file does NOT contain the line
# TODO: Switch to a less hacky way to write to the file?
# TODO: Don't dup IPs (currently duplicated in Vagrant file, must be manually synched)
- name: update hosts file
  shell: echo "192.168.1.101 app" >> /etc/hosts

